type: object
properties:
  limit:
    description: Number of entities per page
    type: integer
    example: 10
  offset:
    description: Index of first entity
    type: integer
    example: 0
  total:
    description: Total number of entities
    type: integer
    example: 1
