swagger: '2.0'
schemes:
  - http
host: 'localhost:8080'
basePath: /manage/v1
x-servers:
  - url: //api.stosyk.io/manage/v1
    description: Default server
  - url: //stosyk-sandbox.herokuapp.com/manage/v1
    description: Sandbox server
info:
  description: >
    Stosyk is a translations management system for software projects.

    The API allows you to work with localization data stored in Stosyk for your
    account.


    # Introduction

    This specification describes the API in 

    [OpenAPI/Swagger
    format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).

    It also uses
    [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo)
    tool and 

    [ReDoc](https://github.com/Rebilly/ReDoc) documentation engine.


    # OpenAPI Specification

    The goal of The OpenAPI Specification is to define a standard,
    language-agnostic interface to REST APIs which

    allows both humans and computers to discover and understand the capabilities
    of the service without access to source

    code, documentation, or through network traffic inspection. When properly
    defined via OpenAPI, a consumer can 

    understand and interact with the remote service with a minimal amount of
    implementation logic. Similar to what

    interfaces have done for lower-level programming, OpenAPI removes the
    guesswork in calling the service.


    # Schema

    The API is only accessible via HTTPS, the base URL is
    https://api.stosyk.io/manage/, and the current version is v1 which presents
    in the base URL for all requests: https://api.stosyk.io/manage/v1/.


    # Authentication

    When you sign up for an account, you will be able to create your first API
    key.

    You can generate as many API keys as you want, manage permissions and delete
    them. 

    You authenticate to the API by providing your secret key in the request
    header.


    Stosyk API offers Bearer authentication.

    It requires sending an `Authorization` header containing the type value
    `Bearer` followed by your authentication token.

    You can control the specific granular permissions and expiration for certain
    token over the [Manage website](https://stosyk.io).

    `TODO:` add an example of usage
  version: 1.0.0
  title: manage.stosyk.io
  contact:
    name: Maksym Koshtenko
    email: maksum.k@gmail.com
  x-logo:
    url: logo.png
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: Projects
  - name: Tags
securityDefinitions:
  bearer_auth:
    description: >
      This scheme relies on authenticating users by having them present a
      standard `Authorization` header containing the value `Bearer` followed by
      their API key / authorization token.
    type: apiKey
    name: Authorization
    in: header
